Actually add Beta Mode
Lekuruu/snowflake pull request #7
Opened 2024-02-19 21:42 UTC by JeffTheRock

When moving back to main, I forgot to update the payout functions.

Oopsie.

2024-02-19 21:45 UTC, Lekuruu commented
You removed the .example_env file. Please add it again

2024-02-19 21:48 UTC, JeffTheRock commented
Readded.

2024-02-19 21:50 UTC, Lekuruu commented
Will review it later, thanks!

2024-02-20 09:59 UTC, Lekuruu requested changes

2024-02-20 09:59 UTC, Lekuruu commented on app/engine/cards.py
> +        self.client.ninja.set_health(0)
Uh.. why?

2024-02-20 09:59 UTC, Lekuruu commented on app/engine/game.py
> +                    if exp_gained == 100:
Maybe make a greater than check here

2024-02-20 14:24 UTC, JeffTheRock commented on app/engine/cards.py
> +        self.client.ninja.set_health(0)
Oops, testing code.
Removed

2024-02-20 14:24 UTC, JeffTheRock commented on app/engine/game.py
> +                    if exp_gained == 100:
Added.

2024-02-20 14:37 UTC, Lekuruu approved these changes
Looking good!

2024-02-20 14:37 UTC, merged